/* Generated by: ./gen_notw.native -n 4 -name notw_4 -compact -standalone */

/*
 * This function contains 16 FP additions, 0 FP multiplications,
 * (or, 16 additions, 0 multiplications, 0 fused multiply/add),
 * 13 stack variables, 0 constants, and 16 memory accesses
 */
void
notw_4 (const R * ri, const R * ii, R * ro, R * io, stride is, stride os,
    INT v, INT ivs, INT ovs)
{
  {
    INT i;
    for (i = v; i > 0;
     i = i - 1, ri = ri + ivs, ii = ii + ivs, ro = ro + ovs, io =
     io + ovs, MAKE_VOLATILE_STRIDE (16, is), MAKE_VOLATILE_STRIDE (16,
                                    os))
      {
    E T3, Tb, T9, Tf, T6, Ta, Te, Tg;
    {
      E T1, T2, T7, T8;
      T1 = ri[0];
      T2 = ri[WS (is, 2)];
      T3 = T1 + T2;
      Tb = T1 - T2;
      T7 = ii[0];
      T8 = ii[WS (is, 2)];
      T9 = T7 - T8;
      Tf = T7 + T8;
    }
    {
      E T4, T5, Tc, Td;
      T4 = ri[WS (is, 1)];
      T5 = ri[WS (is, 3)];
      T6 = T4 + T5;
      Ta = T4 - T5;
      Tc = ii[WS (is, 1)];
      Td = ii[WS (is, 3)];
      Te = Tc - Td;
      Tg = Tc + Td;
    }
    ro[WS (os, 2)] = T3 - T6;
    io[WS (os, 2)] = Tf - Tg;
    ro[0] = T3 + T6;
    io[0] = Tf + Tg;
    io[WS (os, 1)] = T9 - Ta;
    ro[WS (os, 1)] = Tb + Te;
    io[WS (os, 3)] = Ta + T9;
    ro[WS (os, 3)] = Tb - Te;
      }
  }
}

