/* Generated by: ./gen_twiddle.native -n 4 -name twiddle_4 -compact -standalone */

/*
 * This function contains 22 FP additions, 12 FP multiplications,
 * (or, 16 additions, 6 multiplications, 6 fused multiply/add),
 * 13 stack variables, 0 constants, and 16 memory accesses
 */
void
twiddle_4 (R * ri, R * ii, __constant R * W, stride rs, INT mb, INT me, INT ms)
{
  {
    INT m;
    for (m = mb, W = W + (mb * 6); m < me;
     m = m + 1, ri = ri + ms, ii = ii + ms, W =
     W + 6, MAKE_VOLATILE_STRIDE (8, rs))
      {
    E T1, Tp, T6, To, Tc, Tk, Th, Tl;
    T1 = ri[0];
    Tp = ii[0];
    {
      E T3, T5, T2, T4;
      T3 = ri[WS (rs, 2)];
      T5 = ii[WS (rs, 2)];
      T2 = W[2];
      T4 = W[3];
      T6 = FMA (T2, T3, T4 * T5);
      To = FNMS (T4, T3, T2 * T5);
    }
    {
      E T9, Tb, T8, Ta;
      T9 = ri[WS (rs, 1)];
      Tb = ii[WS (rs, 1)];
      T8 = W[0];
      Ta = W[1];
      Tc = FMA (T8, T9, Ta * Tb);
      Tk = FNMS (Ta, T9, T8 * Tb);
    }
    {
      E Te, Tg, Td, Tf;
      Te = ri[WS (rs, 3)];
      Tg = ii[WS (rs, 3)];
      Td = W[4];
      Tf = W[5];
      Th = FMA (Td, Te, Tf * Tg);
      Tl = FNMS (Tf, Te, Td * Tg);
    }
    {
      E T7, Ti, Tn, Tq;
      T7 = T1 + T6;
      Ti = Tc + Th;
      ri[WS (rs, 2)] = T7 - Ti;
      ri[0] = T7 + Ti;
      Tn = Tk + Tl;
      Tq = To + Tp;
      ii[0] = Tn + Tq;
      ii[WS (rs, 2)] = Tq - Tn;
    }
    {
      E Tj, Tm, Tr, Ts;
      Tj = T1 - T6;
      Tm = Tk - Tl;
      ri[WS (rs, 3)] = Tj - Tm;
      ri[WS (rs, 1)] = Tj + Tm;
      Tr = Tp - To;
      Ts = Tc - Th;
      ii[WS (rs, 1)] = Tr - Ts;
      ii[WS (rs, 3)] = Ts + Tr;
    }
      }
  }
}

